/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LayoutContent: typeof import('./src/components/LayoutContent.vue')['default']
    LayoutFooter: typeof import('./src/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLocationAvatar: typeof import('./src/components/RouterLocationAvatar.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeTrigger: typeof import('./src/components/ThemeTrigger.vue')['default']
  }
}
