/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AFloatButtonGroup: typeof import('ant-design-vue/es')['FloatButtonGroup']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASkeletonAvatar: typeof import('ant-design-vue/es')['SkeletonAvatar']
    ASkeletonButton: typeof import('ant-design-vue/es')['SkeletonButton']
    ASkeletonInput: typeof import('ant-design-vue/es')['SkeletonInput']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    EChartsError: typeof import('./src/components/EChartsError.vue')['default']
    EChartsLoading: typeof import('./src/components/EChartsLoading.vue')['default']
    LayoutContent: typeof import('./src/components/LayoutContent.vue')['default']
    LayoutFooter: typeof import('./src/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLocationAvatar: typeof import('./src/components/RouterLocationAvatar.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SessionTable: typeof import('./src/components/SessionTable.vue')['default']
  }
}
